### ISSUE TITLE
move argument handling to core.clj

### ISSUE THREAD

**Issue by etosch** [lspector/taggp#8]
Argument checking and parsing is currently done in the example files. This should be taken care of in core.clj

**Comment by kephale** [comment]
This was done a few versions back, but in a branch. parse-parameters at the end of src/taggp/core.clj in the "tags-replaced-by-defaults" branch is the approach that was being taken.

**Comment by etosch** [comment]
Gah. Is a merge what we want then? Or would it be easier to just copy-and-paste?

**Comment by kephale** [comment]
A merge would probably work, but all you really want is that function. I suspect most of the globals are the same.

**Comment by etosch** [comment]
It looks like this function has the following "extra" globals:
- tagged-with-args
- disallow-tagged-recursion (of course, my code has something like this, but under a different name)
- tag-depth-limit (was this used for recursion?)
- random-seed 

What to do about them?

**Comment by kephale** [comment]
tag-depth-limit was used for enforcing an independent depth limit on trees that contain tags (because tags can grow the trees quite a bit here). This turned out to make a bit of a difference in the results, but it wasn't the missing puzzle piece. 

I say trash all of those variables. random-seed should come back, but that would require porting over the whole thread-local-random stuff that I ported from Clojush a while ago. This should be done from scratch now that your refactoring is so well underway. It isn't a major worry at the moment, but should go back in at some point.

**Comment by etosch** [comment]
Okay, I've added that global, but it's sitting there for now. I'll open a separate issue for the random-seed and close this one.
